// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebTech.Shared.Models
{
    public partial class Employment
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public int EmployerId { get; set; }
        public int EmploymentCourseId { get; set; }
        public int EmploymentTrainingId { get; set; }

        public virtual Employer Employer { get; set; }
        public virtual EmploymentCourse EmploymentCourse { get; set; }
        public virtual EmploymentTraining EmploymentTraining { get; set; }
    }
}