// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebTech.Shared.Models
{
    public partial class Language
    {
        public Language()
        {
            ResourceAttachment = new HashSet<ResourceAttachment>();
        }

        public int Id { get; set; }
        public string Name { get; set; }
        public string English { get; set; }
        public string Chinese { get; set; }
        public string Malay { get; set; }

        public virtual ICollection<ResourceAttachment> ResourceAttachment { get; set; }
    }
}