// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebTech.Shared.Models
{
    public partial class Post
    {
        public Post()
        {
            InverseParent = new HashSet<Post>();
            PostComment = new HashSet<PostComment>();
            PostMeta = new HashSet<PostMeta>();
            Category = new HashSet<Category>();
            Tag = new HashSet<Tag>();
        }

        public long Id { get; set; }
        public long AuthorId { get; set; }
        public long? ParentId { get; set; }
        public string Title { get; set; }
        public string MetaTitle { get; set; }
        public string Slug { get; set; }
        public string Summary { get; set; }
        public bool Published { get; set; }
        public DateTime CreatedAt { get; set; }
        public DateTime? UpdatedAt { get; set; }
        public DateTime? PublishedAt { get; set; }
        public string Content { get; set; }

        public virtual User Author { get; set; }
        public virtual Post Parent { get; set; }
        public virtual ICollection<Post> InverseParent { get; set; }
        public virtual ICollection<PostComment> PostComment { get; set; }
        public virtual ICollection<PostMeta> PostMeta { get; set; }

        public virtual ICollection<Category> Category { get; set; }
        public virtual ICollection<Tag> Tag { get; set; }
    }
}