// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebTech.Shared.Models
{
    public partial class ResourceAttachment
    {
        public int Id { get; set; }
        public string FileName { get; set; }
        public string FilePath { get; set; }
        public int? LanguageId { get; set; }
        public long? FileSize { get; set; }
        public DateTime? DateUpload { get; set; }
        public int? UploderId { get; set; }
        public int ResourceId { get; set; }

        public virtual Language Language { get; set; }
        public virtual Resource Resource { get; set; }
    }
}