// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebTech.Shared.Models
{
    public partial class Resource
    {
        public Resource()
        {
            ResourceAttachment = new HashSet<ResourceAttachment>();
        }

        public int Id { get; set; }
        public string Name { get; set; }
        public int? ResourceCategoryId { get; set; }
        public int? ResourceAgeRangeId { get; set; }

        public virtual ResourceAgeRange ResourceAgeRange { get; set; }
        public virtual ResourceCategory ResourceCategory { get; set; }
        public virtual ICollection<ResourceAttachment> ResourceAttachment { get; set; }
    }
}